// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0BqX4yrGbQO2IDpOQ3L1giwpYEI9Deg',
    appId: '1:622969934256:web:4ac9aecf5536106d854675',
    messagingSenderId: '622969934256',
    projectId: 'muni-ci-pa-lity-project',
    authDomain: 'muni-ci-pa-lity-project.firebaseapp.com',
    storageBucket: 'muni-ci-pa-lity-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDms6M7qY8BIMVBLOzp6winsjxvr-_cZe4',
    appId: '1:622969934256:android:b0ecf443774849d5854675',
    messagingSenderId: '622969934256',
    projectId: 'muni-ci-pa-lity-project',
    storageBucket: 'muni-ci-pa-lity-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTavpJTGGX-aH1l7R2MmNqedXV08wiYU',
    appId: '1:622969934256:ios:5dcfd317ffd1c6a9854675',
    messagingSenderId: '622969934256',
    projectId: 'muni-ci-pa-lity-project',
    storageBucket: 'muni-ci-pa-lity-project.appspot.com',
    iosBundleId: 'com.example.municipality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTavpJTGGX-aH1l7R2MmNqedXV08wiYU',
    appId: '1:622969934256:ios:5dcfd317ffd1c6a9854675',
    messagingSenderId: '622969934256',
    projectId: 'muni-ci-pa-lity-project',
    storageBucket: 'muni-ci-pa-lity-project.appspot.com',
    iosBundleId: 'com.example.municipality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk0BqX4yrGbQO2IDpOQ3L1giwpYEI9Deg',
    appId: '1:622969934256:web:c9b474cb03f753d6854675',
    messagingSenderId: '622969934256',
    projectId: 'muni-ci-pa-lity-project',
    authDomain: 'muni-ci-pa-lity-project.firebaseapp.com',
    storageBucket: 'muni-ci-pa-lity-project.appspot.com',
  );
}
